name: Build APK Bigo Guardian
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: echo "y" | sdkmanager "ndk;25.1.8937393"

      - name: Grant Execute Permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Bigo-Guardian-Final
          path: app/build/outputs/apk/debug/app-debug.apk
